from time import time

from utility.printable import Printable


class Block(Printable):
    """A single block (SPRINT) of our project blockchain.

    Attributes:
        :index: The index of this block (sprint).
        :previous_hash: The hash of the previous block in the blockchain.
        :timestamp: The timestamp of the block (automatically generated by
        default).
        :transactions: A list of transaction (tasks done) which are included in the block.
        :proof: The proof of work/tests (list of tests passed)(prev: number that yielded this block).
        [(test_index, test_result, test_key, test_verb, test_value )]
    """

    def __init__(self, index, previous_hash, transactions, proof, time=time()):
        self.index = index
        self.previous_hash = previous_hash
        self.timestamp = time
        self.transactions = transactions
        self.proof = proof
